### ISSUE TITLE
Parent dropdown in page attributes disappears in 3.0.3 and above

### ISSUE THREAD

**Issue by dmackinn** [kylephillips/wp-nested-pages#258]
The parent dropdown on the page edit screen disappears in both Classic Editor and Gutenberg under the page attributes meta box on Nested Pages version 3.0.3 and above for one of my sites. 

I traced the issue back to wp_dropdown_pages returning an empty string when Nested Pages is activated. Rolling back to Nested Pages version 3.0.2 fixes the issue.

This is on a multi-site setup and not all sites are affected. Deleting all pages and starting from scratch does not fix the issue. Deleting all nestedpages values in wp_options also does not fix the issue.

**Comment by kylephillips** [comment]
This was addressed a while back [here](https://github.com/kylephillips/wp-nested-pages/commit/5610d07ea241faab3256e6bf0200d1effe44521d). Updating to the latest version should clear it up.

**Comment by dmackinn** [comment]
Despite the code update this error is still present in version 3.1.2. It doesn't occur on all sites but it does occur. On my multi-site setup some sites have the parent dropdown and some do not.
